### PR TITLE
WIP: Create initial data models to move to peewee ORM

### PR DESCRIPTION
**Pull request by Rudedog9d**
I started playing around with creating some data models using a Python ORM (just picked https://github.com/coleifer/peewee for it's simplicity/out of a hat). My primary goal was to get better performance out of a more robust DB backend than SQLite, as we use this for a competition and get alot of "db is locked" errors.

Is this something the maintainers are interested in?

### CODE REVIEW

**Comment by vinnybod** [comment]
I agree a move to an ORM is a good call long term. It'll open us up to flexibility for swapping out different databases (MySQL, Postgres) and easier maintenance especially for developers who are less acquanted with the codebase.

I'm not super familiar with peewee, but it looks like a slightly stripped down SQLAlchemy ORM? Is there a benefit to using that over SQLAlchemy?

side note: I went down the path of migrating Empire to SQLAlchemy at one point and then process was pretty taxing. If we can do it in multiple phases, I think it might make the process a bit more approachable.

**Comment by Rudedog9d** [comment]
Hey, thanks for the response. I didn't choose peewee for any particular reason, asside from it looked easy to pick up. (I haven't used any Python ORMs that support SQLite previously to playing with this conversion, I tend to use alot of Mongo). I would guess it could be switched over to SQLAlchemy pretty easily, if that's what the maintainers prefer.

As far doing it in stages - a reasonable first stage would be to replace all the code references to the SQLite DB directly. I replaced the code in `execute_db_query` to use the ORM db connection, which  was _most_ of the queries. As long as the backend is kept as SQLite, it should function as is (maybe even with other backends, I didn't see any sqlite specific querying). 

I think this PR is about 1/2 way to a first stage, the remaining things that I know of off-hand:

- There are a few direct references to the DB file, that are outside of "normal menu execution". (`helpers.py`, `empire.py`, `lib/common/__init__.py`)
- There are about 30 uses of `cur = conn.cursor()`, which could probably be converted over to `execute_db_query` in the short term, or to use an ORM model
- I ran into a handful of issues with things trying to insert data with missing fields. This results in SQLite throwing an error about a null value in a non-nullable field - I'm not entirely sure what I missed in converting the manual SQL Table creation over to ORM, since there wasn't many `NULLABLE` entires in the manual code.
   - An example of this is creating an agent in the DB when a stager calls back to the server, I believe `multi/bash` was causing `agent_language` or something similiar to be null

Let me know if you'd like to see more work on this, and/or if you'd like to go a different direction with the ORM. We use Empire for a local Cyber Competition, and we were looking to improve performance so we could have more users with starkiller. With only ~8 people trying to use Starkiller, we're seeing "sqlite db is locked" errors and really poor performance :(

**Comment by vinnybod** [comment]
I dug into the docs a bit and it seems like Peewee will be fine.

>Let me know if you'd like to see more work on this

I'd love to see some more work on this.

As far as phases go:
I'm fine with starting off with mostly "execute_db_query" in a phase 1 and slowly converting to the `Listener.create(....` and `Listener.get(...` syntax over span of time. One thing to keep in mind is that we don't want to break any of the api endpoints, even if the fields do have some inconsistent syntax so a lot of them might be stuck with `execute_db_query` for the time being.

**Comment by Rudedog9d** [comment]
Cool. We're in prep-mode for our event on November 7th, but I'll try to come back to it after that and get this to a better working/testable state.

**Comment by Cx01N** [comment]
@Rudedog9d I think we may start working on this update next. Were you still working on this or should we pick up where you left off?

**Comment by Rudedog9d** [comment]
@Cx01N I haven't had a chance to continue work on this at all. It'd be awesome to see someone else pick it up.

Also, I saw you guys released the CLI as multi-user - I'm excited to test that out :smiley:

**Comment by vinnybod** [comment]
Closing this since we're working on a sqlalchemy implementation.

**Pull request closed without merging**
