### PR TITLE
Fixxed agent/server module version check

### PR DESCRIPTION
**Pull request by Jackrin**
The check was not made correctly leading to a version like "3.10" to be considered older than "3.9", because of string to float coversion.

### CODE REVIEW

**Comment by Cx01N** [comment]
Can you run `sudo poetry run black .` and `sudo poetry run isort .`  to get the lint template to pass?

**Review by vinnybod — CHANGES_REQUESTED** [review]
Unfortunately, the new code is also flawed. Consider a comparison of 3.6 vs 2.7.  I think what we need is an actual semver comparison.

This could be accomplished with the [packaging](https://packaging.pypa.io/en/latest/version.html#packaging.version.Version) library.

**Comment by Jackrin** [comment]
Fixxed the code, now it should work for all cases.

**Review by vinnybod — APPROVED** [review]

**Comment by vinnybod** [comment]
Looks like its failing on the formatting cehcks. Can you run the formatters on the code?
https://github.com/BC-SECURITY/Empire/blob/master/.github/CONTRIBUTING.md#code-formatting

**Pull request merged**
