### PR TITLE
Updates for installer

### PR DESCRIPTION
**Pull request by Pernat1y**
Added Fedora Linux support for installer. Tested on supported Fedora versions (32 and 33).
Small refactoring.

### CODE REVIEW

**Comment by vinnybod** [comment]
Thanks for this contribution! At the moment, we think its best to only include our 3 supported OSs in the install script. However, I just pushed up an update to the wiki that adds a section for additional community-driven install scripts. You would just write your individual Fedora script and include it at the bottom of [this page](https://github.com/BC-SECURITY/Empire/blob/dev/wiki/Installation.md#community-supported-operating-systems). Let me know what you think.

**Comment by Pernat1y** [comment]
You still can have other OSes in the installer, but marked as "beta" / "unsupported" / "community-supported".
If no, then I will remove Fedora support and just keep updates to existing code in this PR.

**Comment by Hubbl3** [comment]
@Pernat1y the problem is even if we mark it "unsupported" there will still be people opening issues and expecting us to fix those issues in the future. We will definitely except your other updates though.

**Comment by Pernat1y** [comment]
Removed Fedora. Leaving just generic updates to installer.

**Review by vinnybod — APPROVED** [review]

**Pull request merged**
